# Generated by Django 4.2.23 on 2025-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='blog_pdfs/'),
        ),
    ]
